# -*- coding: utf-8 -*-
"""opencv_test.ipynb

Automatically generated by Colaboratory.

"""

import cv2
import numpy as np
working_dir = "/content/drive/MyDrive/opencv/"

img = cv2.imread(working_dir + "image2.jpg", 0)

# cv2.THRESH_BINARY     : >127 =255, <127 =0
# cv2.THRESH_BINARY_INV : >127 =0,   <127 =255
# cv2.THRESH_TRUNC      : >127 =127
# cv2.THRESH_TOZERO     : <127 =0
# cv2.THRESH_TOZERO_INV : >127 =0
ret, out1 = cv2.threshold(img, 127, 255, cv2.THRESH_BINARY)
cv2.imwrite(working_dir + "out1.png", out1)

# block size: 11x11
# constant: thres = MEAN/GAUSSIAN - 2 
out2 = cv2.adaptiveThreshold(img, 255, cv2.ADAPTIVE_THRESH_MEAN_C, cv2.THRESH_BINARY, 11, 2) 
out3 = cv2.adaptiveThreshold(img, 255, cv2.ADAPTIVE_THRESH_GAUSSIAN_C, cv2.THRESH_BINARY, 11, 2) 
cv2.imwrite(working_dir + "out2.png", out2)
cv2.imwrite(working_dir + "out3.png", out3)

# Otsu's
ret, out4 = cv2.threshold(img, 0, 255, cv2.THRESH_BINARY+cv2.THRESH_OTSU)
cv2.imwrite(working_dir + "out4.png", out4)
