# -*- coding: utf-8 -*-
"""opencv_test.ipynb

Automatically generated by Colaboratory.

"""

import cv2
from google.colab.patches import cv2_imshow

face_cascade = cv2.CascadeClassifier(cv2.data.haarcascades +'haarcascade_frontalface_default.xml')
eye_cascade = cv2.CascadeClassifier(cv2.data.haarcascades +'haarcascade_eye_tree_eyeglasses.xml')
# print(cv2.data.haarcascades), /usr/local/lib/python3.7/dist-packages/cv2/data/

img = cv2.imread("/content/drive/MyDrive/Colab/image5.JPG")
img = cv2.resize(img, (250,300), interpolation = cv2.INTER_AREA)
gray_img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

faces = face_cascade.detectMultiScale(gray_img)
for (x,y,w,h) in faces:
  center = (x+w//2, y+h//2)
  img = cv2.ellipse(img, center, (w//2, h//2), 0, 0, 360, (255,0,0), 4)

  faceROI = gray_img[y:y+h, x:x+w]
  eyes = eye_cascade.detectMultiScale(faceROI)
  for (x2,y2,w2,h2) in eyes:
    cv2.rectangle(img, (x+x2,y+y2), (x+x2+w2, y+y2+h2), (0,255,0), 2)

cv2_imshow(img)