# -*- coding: utf-8 -*-
"""opencv_test.ipynb

Automatically generated by Colaboratory.

"""

import cv2
import numpy as np
from google.colab.patches import cv2_imshow

# cv2.resize
img = np.ones([4,4])

img[:2,:2] = 255
print(img)

img_INTER_AREA = cv2.resize(img, (8,8), interpolation = cv2.INTER_AREA)
print(img_INTER_AREA)

img_INTER_NEAREST = cv2.resize(img, (8,8), interpolation = cv2.INTER_NEAREST)
print(img_INTER_NEAREST)

img_INTER_LINEAR = cv2.resize(img, (8,8), interpolation = cv2.INTER_LINEAR)
print(img_INTER_LINEAR)

img_INTER_CUBIC = cv2.resize(img, (8,8), interpolation = cv2.INTER_CUBIC)
print(img_INTER_CUBIC)

# =========================
scale = 2
width = img.shape[1] * scale
height = img.shape[0] * scale
img_INTER_AREA = cv2.resize(img, (width,height), interpolation = cv2.INTER_AREA)
print(img_INTER_AREA)
