# -*- coding: utf-8 -*-
"""opencv_test.ipynb

Automatically generated by Colaboratory.

"""

import cv2
import numpy as np
from google.colab.patches import cv2_imshow

# HSV (hue, saturation, value)
# hue channel models the color type, it is very useful in image processing tasks that need to segment objects based on its color
# value channel describes the brightness or the intensity of the color

img_path = "/content/drive/MyDrive/Colab/image1.jpg"
img = cv2.imread(img_path)
img = cv2.resize(img, (img.shape[1]//10, img.shape[0]//10), cv2.INTER_AREA)

img_HSV = cv2.cvtColor(img, cv2.COLOR_BGR2HSV)

lower_bound = np.array([20,20,20])
upper_bound = np.array([200,200,200])
img_threshold = cv2.inRange(img_HSV, lower_bound, upper_bound)
cv2_imshow(img_threshold)

lower_bound = np.array([20,20,20])
upper_bound = np.array([30,200,200])
img_threshold = cv2.inRange(img_HSV, lower_bound, upper_bound)
cv2_imshow(img_threshold)

# ===========================
H,S,V = cv2.split(img_HSV)
cv2_imshow(H)
