
version: '3'
services:
    my-module:
        build:
            context: .
        image: my-Image:v8.1.1
        container_name: my-module
        environment:
            - VARIABLE_A=90
            - VARIABLE_B=myString
        volumes:
             - /opt/local_folder/:/opt/myFolder/   # local:docker
        # network_mode: "host"
        ports:
            - 5000:5000

        # restart: always
        # command: python /opt/xxx.py
        # command: tail -f /dev/null  # 不執行任何程式, just keep container alive
